spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: auth_route
          uri: lb://order-server
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: order_route
          uri: lb://order-server
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1
        - id: product_route
          uri: lb://order-server
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: stock_route
          uri: lb://stock-server
          predicates:
            - Path=/api/stock/**
          filters:
            - StripPrefix=1
        - id: praise_send_route
          uri: lb://integrated-praise-provider
          predicates:
            - Path=/api/praise/send/**
          filters:
            - StripPrefix=1
        - id: praise_query_route
          uri: lb://integrated-praise-consumer
          predicates:
            - Path=/api/praise/count/**,/api/praise/list/**,/api/praise/recent/**
          filters:
            - StripPrefix=1
