author: wangyong

spring:
  datasource:
    username: root
    password: 114134
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #初始化时运行sql脚本
    schema: classpath:sql/schema.sql
    initialization-mode: never
    
#设置mybatis-plus
mybatis-plus:
  mapper-locations: classpath:com/tulingxueyuan/order/mapper/*Mapper.xml
  type-aliases-package: com.tulingxueyuan.order.pojo
  configuration:
    map-underscore-to-camel-case: true

# file模式的配置
seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-group
  service:
    vgroup-mapping:
      order-server-group: default
    grouplist:
      default: 127.0.0.1:8091
